# Generated by Django 5.1 on 2024-10-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_alter_movie_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="actors",
            field=models.CharField(default="Unknown", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="director",
            field=models.CharField(default="Unknown", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genre",
            field=models.CharField(
                choices=[
                    ("ACTION", "Action"),
                    ("COMEDY", "Comedy"),
                    ("DRAMA", "Drama"),
                    ("FANTASY", "Fantasy"),
                    ("HORROR", "Horror"),
                    ("SCI_FI", "Science Fiction"),
                    ("ROMANCE", "Romance"),
                    ("THRILLER", "Thriller"),
                    ("DOCUMENTARY", "Documentary"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
