# Generated by Django 5.1 on 2024-10-13 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_movie_average_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="average_rating",
            field=models.FloatField(
                default=None,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
