# Generated by Django 5.1 on 2024-10-10 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "release_year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1800),
                            django.core.validators.MaxValueValidator(2024),
                        ]
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("ACTION", "Action"),
                            ("COMEDY", "Comedy"),
                            ("DRAMA", "Drama"),
                            ("FANTASY", "Fantasy"),
                            ("HORROR", "Horror"),
                            ("SCI_FI", "Science Fiction"),
                            ("ROMANCE", "Romance"),
                            ("THRILLER", "Thriller"),
                            ("DOCUMENTARY", "Documentary"),
                        ],
                        max_length=20,
                    ),
                ),
                ("director", models.CharField(max_length=100)),
                ("actors", models.CharField(max_length=100)),
            ],
        ),
    ]
