# Generated by Django 5.1 on 2024-10-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_alter_movie_actors_alter_movie_director_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="genre",
            field=models.CharField(
                choices=[
                    ("ACTION", "Action"),
                    ("COMEDY", "Comedy"),
                    ("DRAMA", "Drama"),
                    ("FANTASY", "Fantasy"),
                    ("HORROR", "Horror"),
                    ("SCI_FI", "Science Fiction"),
                    ("ROMANCE", "Romance"),
                    ("THRILLER", "Thriller"),
                    ("DOCUMENTARY", "Documentary"),
                    ("ANIMATION", "Animation"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
