# Generated by Django 5.1 on 2024-10-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0007_alter_movie_average_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="actors",
        ),
    ]
