# Generated by Django 5.1 on 2024-10-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_remove_movie_actors"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="duration",
            field=models.IntegerField(default=0),
        ),
    ]
